### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by ReaperXD1** [MRX8024/chopper-resonance-tuner#22]
Hi there, I have just installed the chopper resonance tuner, however I continue to get this error when attempting to run the macro.
![image](https://github.com/MRX8024/chopper-resonance-tuner/assets/110054997/82a9801b-5681-409c-bdce-04c2a2e333f4)

I don't know what is going on, I've even done the manual installation.

I am running a CB1 if that changes anything.

**Comment by MRX8024** [comment]
Hi, pin a klippy.log

**Comment by ReaperXD1** [comment]
Thanks for your quick reply. I've had to compress it as it was over githubs file size limit.
[klippy (3).zip](https://github.com/MRX8024/chopper-resonance-tuner/files/15487287/klippy.3.zip)

**Comment by MRX8024** [comment]
Please update to the latest version, I have fixed some possible errors  there

**Comment by ReaperXD1** [comment]
Still having this issue. Does it matter that I am using the BTT Klipper fork required for the new Eddy sensor?
![image](https://github.com/MRX8024/chopper-resonance-tuner/assets/110054997/b1f6e059-a2d5-4052-b9a6-de73d223a764)
[klippy.log](https://github.com/MRX8024/chopper-resonance-tuner/files/15492824/klippy.log)

**Comment by MRX8024** [comment]
Try to install original klipper, which already support eddy. But it’s strange if btt broke something in their fork. And can you attach link to this fork please

**Comment by ReaperXD1** [comment]
Original Klipper doesn't support the BTT Eddy unfortunately. 

https://github.com/bigtreetech/Eddy/tree/master - Eddy github
https://github.com/bigtreetech/klipper - BTT Klipper

**Comment by MRX8024** [comment]
https://www.klipper3d.org/Config_Reference.html#probe_eddy_current

**Comment by ReaperXD1** [comment]
I will try to get it working, give me a little :)

**Comment by ReaperXD1** [comment]
Hi there, same story, on latest Klipper
[Uploading klippy (2).log…]()

**Comment by MRX8024** [comment]
Since jinja2 cannot show the exact location of the error, I placed tags in the code. Please replace the macro, for example by replacing 'include' line
[chopper_tune_test.cfg.txt](https://github.com/MRX8024/chopper-resonance-tuner/files/15501745/chopper_tune_test.cfg.txt)

**Comment by ReaperXD1** [comment]
Hi, attached is the new Klippy log.
[klippy (4).log](https://github.com/user-attachments/files/15507634/klippy.4.log)

**Comment by MRX8024** [comment]
I think I found a mistake..
Try this - [chopper_tune_test.cfg.txt](https://github.com/user-attachments/files/15511216/chopper_tune_test.cfg.txt)

**Comment by ReaperXD1** [comment]
Hi there I'll give it a shot now!

**Comment by ReaperXD1** [comment]
It works! Thank you so much for your work! What was the issue?

**Comment by MRX8024** [comment]
Script was supposed to get the sense_resistor value from config, which was not specified there. Now after c67b6c4 I take it from another place. Thanks for the feedback, if you have no questions left, I think we can close this issue.

-Maxim
